// <auto-generated />
namespace Alcom.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class version10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version10));
        
        string IMigrationMetadata.Id
        {
            get { return "202002041528270_version1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
